Allow end user to add additional packages to the image
pi-hole/docker-pi-hole pull request #1423
Opened 2023-09-03 12:23 UTC by PromoFaux

### **What does this PR aim to accomplish?:**

Heavily inspired by [Netdata](https://github.com/netdata/netdata/tree/master/packaging/docker#adding-extra-packages-at-runtime)'s container.

Some people like `nano`, some people like `vim`. Why force them to use the better of the two? ;)

Also, anyone can `apk add` inside the container - this just makes it easier for those of us that always like to have whatever additional tools we need inside the container for debugging

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

2023-09-03 20:57 UTC, yubiuser requested changes
Documentation required.

2023-09-21 03:43 UTC, rdwebdesign commented on README.md
> +| `ADDITIONAL_PACKAGES`| unset | Comma separated list of APKs | HERE BE DRAGONS. Mostly for development purposes, this just makes it easier for those of us that always like to have whatever additiona
"Comma separated" or "space separated" list?

2023-09-25 17:29 UTC, rdwebdesign commented on src/start.sh
> +      echo "  [i] Installing additional packages."
Do you think we should print the additional packages or this is too much?

```suggestion
      echo "  [i] Installing additional packages: ${ADDITIONAL_PACKAGES}."
```

2023-09-25 19:13 UTC, rdwebdesign approved these changes

2023-09-25 20:23 UTC, yubiuser approved these changes

2023-09-25 21:36 UTC, merged