Default DNS Upstream
pi-hole/docker-pi-hole pull request #1608
Opened 2024-06-30 20:16 UTC by PromoFaux

### **What does this PR aim to accomplish?:**

See https://discourse.pi-hole.net/t/how-to-modify-upstream-server-only-via-gui-on-v6/70943/13?u=promofaux

Lower the barrier to entry/reduce confusion by setting DNS upstreams to `8.8.8.8;8.8.4.4` if we detect that it has not already been set by either the environment variable or config file. Falling back to a default rather than hard-exiting is probably more user friendly, on reflection.

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

2024-06-30 20:27 UTC, yubiuser reviewed
Why not only remove the `exit 1` line and keep the upstream unset + print the warning?

2024-06-30 20:30 UTC, PromoFaux commented
Because ultimately nobody will read the warning. 

I originally put the `exit 1` to make it extremely obvious that something needed configuring, but if by defaulting it does not need to be configured immediately.

If we don't default and also don't exit, the startup checks wont always work (e.g in the case of the container having itself as a resolver - either via compose/run or via the host's settings)

2024-06-30 21:37 UTC, PromoFaux commented on test/tests/test_general.py
> +        grep 'jmpret\|terminated' /var/log/pihole/FTL.log
Yeah, nice trick here!

2024-07-01 14:29 UTC, Gontier-Julien commented
Might i suggest on using maybe Cloudflare Dns (1.1.1.1 & 1.0.0.1) or Quad9 Dns (9.9.9.9 & 149.112.112.112)?

My reasoning behind this is that for Cloudflare is the fastest dns out here, while Quad9 offer better privacy but slower.
Both have a privacy policies meanwhile Google Dns as none as far as i'm aware.

Providing a faster and/or more private dns upstream would be better i think for some default.

Also Cloudflare dns i widely know so i don't think many people would mind + having as faster (even slightly) dns is always a better user experience.

2024-07-02 19:01 UTC, yubiuser requested changes

2024-07-02 19:01 UTC, yubiuser commented on src/bash_functions.sh
>      # If getFTLConfigValue "dns.upstreams" returns [], exit the container. We need upstream servers to function!
```suggestion
    # If getFTLConfigValue "dns.upstreams" returns [], default to Google's DNS server
```

2024-07-02 19:13 UTC, yubiuser approved these changes

2024-07-02 19:13 UTC, merged