Feature/self contained docker run
pi-hole/docker-pi-hole pull request #649
Opened 2020-07-10 13:51 UTC by aviadra

## Description
Makes it so the "docker_run.sh" script, is self contained and doesn't require the user to fill in so many blanks.

## Motivation and Context
This is to make the docker installation method, as smooth as the regular one. One can install by simply curling the script into the bash

## How Has This Been Tested?
Test on:

- My raspberry pi running ubuntu 20.04
- AWS amd64 instance of Ubuntu 20.04
- AWS arm instance of Ubuntu 20.04
- AWS amd64 instance of RHEL8.

The only thing I changed is that I pointed the install script to my repo and my branch, as this is not part of the main repo yet.

This is my first PR to free software, I hope you like it.

2020-07-10 15:35 UTC, diginc commented
I like the sentiment of helping users get going quickly and easily.  I'll discuss with the team before making a more complete reply but I'll drop my first reactions:

- I prefer docker-compose as a default option (it was moved to the top of readme a while back)
- I've been seeing more success and recommendations for people to just use macvlan to avoid issues to the point I'm thinking it should be default and if we have to bootstrap to help start the container, that should be used perhaps.

2020-07-10 15:52 UTC, aviadra commented
Thank you for the prompt response.
Looking forward to hearing from you again.

On Fri, Jul 10, 2020, 18:35 Adam Hill <notifications@github.com> wrote:

> I like the sentiment of helping users get going quickly and easily. I'll
> discuss with the team before making a more complete reply but I'll drop my
> first reactions:
>
>    - I prefer docker-compose as a default option (it was moved to the top
>    of readme a while back)
>    - I've been seeing more success and recommendations for people to just
>    use macvlan to avoid issues to the point I'm thinking it should be default
>    and if we have to bootstrap to help start the container, that should be
>    used perhaps.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-hole/docker-pi-hole/pull/649#issuecomment-656738996>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP4WRMOGLQOB4FTVTX3AZ3R24YM7ANCNFSM4OWTSN4A>
> .
>

2020-10-03 18:01 UTC, dschaper requested changes

2020-10-03 18:01 UTC, dschaper commented on docker_run.sh
> +#!/usr/bin/env zsh
Use bash or pure shell.

2020-10-03 18:02 UTC, dschaper commented
>     * I prefer docker-compose as a default option (it was moved to the top of readme a while back)

Same here. Other options are environmental variables, [envdir](http://manpages.ubuntu.com/manpages/trusty/man8/envdir.8.html) is great for this.

2020-10-03 18:04 UTC, aviadra commented
Thank you. I was developing on a mac... I'll change it

On Sat, Oct 3, 2020, 21:01 Dan Schaper <notifications@github.com> wrote:

> *@dschaper* requested changes on this pull request.
> ------------------------------
>
> In docker_run.sh
> <https://github.com/pi-hole/docker-pi-hole/pull/649#discussion_r499168691>
> :
>
> > -    -p 53:53/tcp -p 53:53/udp \
> -    -p 80:80 \
> -    -p 443:443 \
> -    -e TZ="America/Chicago" \
> -    -v "$(pwd)/etc-pihole/:/etc/pihole/" \
> -    -v "$(pwd)/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
> -    --dns=127.0.0.1 --dns=1.1.1.1 \
> -    --restart=unless-stopped \
> -    --hostname pi.hole \
> -    -e VIRTUAL_HOST="pi.hole" \
> -    -e PROXY_LOCATION="pi.hole" \
> -    -e ServerIP="127.0.0.1" \
> -    pihole/pihole:latest
> -
> -printf 'Starting up pihole container '
> +#!/usr/bin/env zsh
>
> Use bash or pure shell.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-hole/docker-pi-hole/pull/649#pullrequestreview-501563509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP4WRKX3W6GYYTESKTKA33SI5RJDANCNFSM4OWTSN4A>
> .
>

2021-04-14 13:42 UTC, lightswitch05 commented
Do we really want to encourage more `curl | bash` type behavior?

Beyond that, this script is now making changes to the host's `systemd-resolved` configuration. I understand that is a common hurdle for people to overcome when getting started with this on Ubuntu, but the last thing I expect when running docker containers is for it to make configuration changes on my host.

I'm all for making things easier for people to get started, but this version of ` docker_run.sh` goes way beyond just a docker-run command.

2021-04-14 14:15 UTC, aviadra commented
I must agree with you.
I myself have neglected this way, because it seems to not do what it
should, and other stuff mentioned.

On Wed, Apr 14, 2021, 16:43 Daniel ***@***.***> wrote:

> Do we really want to encourage more curl | bash type behavior?
>
> Beyond that, this script is now making changes to the host's
> systemd-resolved configuration. I understand that is a common hurdle for
> people to overcome when getting started with this on Ubuntu, but the last
> thing I expect when running docker containers is for it to make
> configuration changes on my host.
>
> I'm all for making things easier for people to get started, but this
> version of docker_run.sh goes way beyond just a docker-run command.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pi-hole/docker-pi-hole/pull/649#issuecomment-819528318>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAP4WRLKN5E75F6NOGSDH6DTIWLW7ANCNFSM4OWTSN4A>
> .
>

2021-12-09 17:49 UTC, PromoFaux commented
Closing as stale - Feel free to reopen if this needs revisting

2021-12-09 17:49 UTC, closed without merging